name: Linting

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev", "main" ]

jobs:

  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: |
            3.10
            3.11
        cache:
    - name: Install dependencies
      run: pip install .[dev]
    - name: Run the precommits
      run: pre-commit run -a
